version: '3'
services:
  web:
    image: nginx
    volumes:
        - "./app:/app"
        - "./nginx:/nginx"
        - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "3002:80"